//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_DB_PROJECT
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SalesDBEntities : DbContext
    {
        public SalesDBEntities()
            : base("name=SalesDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TBLACTION> TBLACTIONs { get; set; }
        public virtual DbSet<TBLCATEGORY> TBLCATEGORies { get; set; }
        public virtual DbSet<TBLCUSTOMER> TBLCUSTOMERs { get; set; }
        public virtual DbSet<TBLEMPLOYEE> TBLEMPLOYEEs { get; set; }
        public virtual DbSet<TBLPRODUCT> TBLPRODUCTs { get; set; }
    }
}
