//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_DB_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLACTION
    {
        public int ACTIONID { get; set; }
        public Nullable<int> PRODUCT { get; set; }
        public Nullable<int> CUSTOMER { get; set; }
        public Nullable<short> EMPLOYEE { get; set; }
        public Nullable<int> NUMBER { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public Nullable<System.DateTime> DATE { get; set; }
    
        public virtual TBLCUSTOMER TBLCUSTOMER { get; set; }
        public virtual TBLEMPLOYEE TBLEMPLOYEE { get; set; }
        public virtual TBLPRODUCT TBLPRODUCT { get; set; }
    }
}
