//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQL_DB_PROJECT
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLPRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLPRODUCT()
        {
            this.TBLACTIONs = new HashSet<TBLACTION>();
        }
    
        public int PRODUCTID { get; set; }
        public string PRODUCTNAME { get; set; }
        public string PRODUCTBRAND { get; set; }
        public Nullable<byte> CATEGORY { get; set; }
        public Nullable<decimal> PRODUCTBUYPRICE { get; set; }
        public Nullable<decimal> PRODUCTSELLSPRICE { get; set; }
        public Nullable<short> PRODUCTSTOCK { get; set; }
        public Nullable<bool> POSITION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLACTION> TBLACTIONs { get; set; }
        public virtual TBLCATEGORY TBLCATEGORY { get; set; }
    }
}
